# -*- mode: Yaml; -*-
# Default options.
# Can also be specific for a set of samples, libraries, and lanes,
# by including the "Options" hierarchy at the same level as those
# samples, libraries, or lanes below.
Options:
  # Sequencing platform, see SAM/BAM reference for valid values
  Platform: Illumina
  # Quality offset for Phred scores, either 33 (Sanger/Illumina 1.8+)
  # or 64 (Illumina 1.3+ / 1.5+). For Bowtie2 it is also possible to
  # specify 'Solexa', to handle reads on the Solexa scale. This is
  # used during adapter-trimming and sequence alignment
  QualityOffset: 33

  # Settings for trimming of reads, see AdapterRemoval man-page
  AdapterRemoval:
    # Set and uncbowtieeomment to override defaults adapter sequences
#     --adapter1: AGATCGGAAGAGCACACGTCTGAACTCCAGTCACNNNNNNATCTCGTATGCCGTCTTCTGCTTG
#     --adapter2: AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGTGGTCGCCGTATCATT
    # Some BAM pipeline defaults differ from AR defaults;
    # To override, change these value(s):
    --mm: 3
    --minlength: 25
    # Extra features enabled by default; change 'yes' to 'no' to disable
    --collapse: yes
    --trimns: yes
    --trimqualities: yes

  # Settings for aligners supported by the pipeline
  Aligners:
    # Choice of aligner software to use, either "BWA" or "Bowtie2"
    Program: Bowtie2

    Bowtie2:
      # Filter aligned reads with a mapping quality (Phred) below this value
      MinQuality: 0
      # Filter reads that did not map to the reference sequence
      FilterUnmappedReads: yes
      # Examples of how to add additional command-line options
#      --trim5: 5
#      --trim3: 5
      # Note that the colon is required, even if no value is specified
      --very-sensitive-local:
      # Example of how to specify multiple values for an option
#      --rg:
#        - CN:SequencingCenterNameHere
#        - DS:DescriptionOfReadGroup

  # Command-line options for mapDamage; use long-form options(--length not -l):
  mapDamage:
    # By default, the pipeline will downsample the input to 100k hits
    # when running mapDamage; remove to use all hits
    --downsample: 100000

  # Set to 'yes' exclude a type of trimmed reads from alignment / analysis;
  # possible read-types reflect the output of AdapterRemoval
  ExcludeReads:
    # Exclude single-end reads (yes / no)?
    Single: no
    # Exclude non-collapsed paired-end reads (yes / no)?
    Paired: no
    # Exclude paired-end reads for which the mate was discarded (yes / no)?
    Singleton: no
    # Exclude overlapping paired-ended reads collapsed into a single sequence
    # by AdapterRemoval (yes / no)?
    Collapsed: no
    # Like 'Collapsed', but only for collapsed reads truncated due to the
    # presence of ambiguous or low quality bases at read termini (yes / no).
    CollapsedTruncated: no

  # Optional steps to perform during processing.
  Features:
    # If set to 'filter', PCR duplicates are removed from the output files; if set to
    # 'mark', PCR duplicates are flagged with bit 0x400, and not removed from the
    # output files; if set to 'no', the reads are assumed to not have been amplified.
    PCRDuplicates: filter
    # Set to 'no' to disable mapDamage; set to 'plot' to build basic mapDamage plots;
    # set to 'model' to build plots and post-mortem damage models; and set to 'rescale'
    # to build plots, models, and BAMs with rescaled quality scores. All analyses are
    # carried out per library.
    mapDamage: no
    # Generate coverage information for the final BAM and for each 'RegionsOfInterest'
    # specified in 'Prefixes' (yes / no).
    Coverage: yes
    # Generate histograms of number of sites with a given read-depth, from 0 to 200,
    # for each BAM and for each 'RegionsOfInterest' specified in 'Prefixes' (yes / no).
    Depths: yes
    # Generate summary table for each target (yes / no)
    Summary: yes

# Map of prefixes by name, each having a Path, which specifies the location of the
# BWA/Bowtie2 index, and optional regions for which additional statistics are produced.
Prefixes:
  my_genome:
    Path:  /mss_users/ltursunova/cow/oc2_genome.fasta


  SRR5949621:
   SRR5949621:
    Path:  /mss_users/ltursunova/cow/new2/SRR5949621*fastq
  SRR5949624:
   SRR5949624:
    Path:  /mss_users/ltursunova/cow/new2/SRR5949624*fastq
  SRR5949634:
   SRR5949634:
    Path:  /mss_users/ltursunova/cow/new2/SRR5949634*fastq
  SRR6485265:
   SRR6485265:
    Path:  /mss_users/ltursunova/cow/new2/SRR6485265*fastq
  SRR11020300:
   SRR11020300:
    Path:  /mss_users/ltursunova/cow/new2/SRR11020300*fastq
  SRR17908655:
   SRR17908655:
    Path:  /mss_users/ltursunova/cow/new2/SRR17908655*fastq
  SRR5949623:
   SRR5949623:
    Path:  /mss_users/ltursunova/cow/new2/SRR5949623*fastq
  SRR6485281:
   SRR6485281:
    Path:  /mss_users/ltursunova/cow/new2/SRR6485281*fastq
  SRR17044867:
   SRR17044867:
    Path:  /mss_users/ltursunova/cow/new2/SRR17044867*fastq
  SRR5949630:
   SRR5949630:
    Path:  /mss_users/ltursunova/cow/new2/SRR5949630*fastq
  SRR6485284:
   SRR6485284:
    Path:  /mss_users/ltursunova/cow/new2/SRR6485284*fastq
  SRR11020211:
   SRR11020211:
    Path:  /mss_users/ltursunova/cow/new2/SRR11020211*fastq
  SRR17908654:
   SRR17908654:
    Path:  /mss_users/ltursunova/cow/new2/SRR17908654*fastq
  SRR17908659:
   SRR17908659:
    Path:  /mss_users/ltursunova/cow/new2/SRR17908659*fastq
  SRR17908658:
   SRR17908658:
    Path:  /mss_users/ltursunova/cow/new2/SRR17908658*fastq
  SRR5949632:
   SRR5949632:
    Path:  /mss_users/ltursunova/cow/new2/SRR5949632*fastq
