install.packages('vcfR') 
install.packages('vegan')
install.packages('ggplot2')
install.packages('ggpubr')
library(vcfR)    
library(vegan)
library(ggplot2)
library(ggpubr)
snps <- vcfR::read.vcfR("re.12.01.miss0.vcf", convertNA  = TRUE)
